#!/bin/bash

#############################################
## env settings
SELF=$(readlink -f "$0")
HERE=${SELF%/*}
#############################################

LANG=$LANG \
APPIMAGE=$APPIMAGE \
APPDIR=$APPDIR \
OWD=$OWD \
ARGV0=$ARGV0 \
"$HERE"/opt/myapp/myapp_script/myapp "$@"
