name: "test-build"

  #on:
  #  push:
  #    branches:
  #      - "main"

on: [workflow_dispatch]

jobs:
  pre-release:
    runs-on: "ubuntu-latest"
    container:
      image: ubuntu:18.04
      options: --privileged

    steps:
      - name: Install packages
        run: |
          apt-get update -y
          apt-get install -y wget binutils

      - name: checkout current repo code
        uses: actions/checkout@v3
        with:
          repository: zerobikappa/appimage-myapp-appdir-template
          path: appimage-myapp-appdir-template

      - name: update and build
        run: |
          wget -c "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks" -O appimage-myapp-appdir-template/usr/bin/winetricks
          chmod u+x appimage-myapp-appdir-template/usr/bin/winetricks
          wget -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" -O  appimagetool.AppImage
          chmod u+x appimagetool.AppImage
          mv ./appimage-myapp-appdir-template/backup/unionfs-fuse*.deb .
          ./appimage-myapp-appdir-template/.remove-appdir-git.sh

          ar x unionfs-fuse*amd64.deb
          tar Jxvf data.tar.xz
          mv -f usr/bin/unionfs appimage-myapp-appdir-template/usr/bin/
          ARCH=x86_64 ./appimagetool.AppImage appimage-myapp-appdir-template

          #ar x unionfs-fuse*arm64.deb
          #tar Jxvf data.tar.xz
          #mv -f usr/bin/unionfs appimage-myapp-appdir-template/usr/bin/
          #ARCH=aarch64 ./appimagetool.AppImage appimage-myapp-appdir-template

          #ar x unionfs-fuse*i386.deb
          #tar Jxvf data.tar.xz
          #mv -f usr/bin/unionfs appimage-myapp-appdir-template/usr/bin/
          #ARCH=i386 ./appimagetool.AppImage appimage-myapp-appdir-template

